[tools]
dotnet-core = "latest"
go = "1.26.7"
java = "corretto-11"
node = "24"
"npm:@evenrealities/even-terminal" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:firebase-tools" = "latest"
pnpm = "latest"
python = "3.13.3"
terraform = "latest"
uv = "latest"
zellij = "latest"

[settings]
legacy_version_file = true
idiomatic_version_file_enable_tools = ["go", "node", "terraform"]
go_set_gobin = true
