name: Setup Golang
description: Setup Golang

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: scripts/dofy/go.mod
        cache-dependency-path: scripts/dofy/go.sum
    - name: Set up xc
      uses: joerdav/setup-xc@eaed99ccd40453d5ab8fe50e7dfd033e6f302e98 # v1
    - name: Run `xc init`
      shell: bash
      working-directory: scripts/dofy
      run: |
        xc init
