- name: Set dir_symlinks
  ansible.builtin.set_fact:
    replace_list:
      - ".config"
      - ".local/share"
    dir_symlinks:
      - ".local/share/navi/cheats/"

- name: Find all files in config dir
  ansible.builtin.find:
    paths: "{{ vars.config_dir }}"
    hidden: true
    recurse: true
  register: config_files

- name: Get file paths from config_files
  ansible.builtin.set_fact:
    config_paths: "{{ config_files.files | map(attribute='path') | map('replace', vars.config_dir + '/', '') | list }}"

- name: Get config items (.config and .local/share patterns)
  ansible.builtin.set_fact:
    config_items: "{{ config_paths | select('match', '.*(' + replace_list | join('|') + ')') | list }}"

- name: Transform config paths using patterns
  ansible.builtin.set_fact:
    config_items: "{{ config_items | map('regex_replace', '^([^/]+)/' + item | regex_escape + '/(.*)$', item + '/\\1/\\2') | list }}"
  loop: "{{ replace_list }}"

- name: Remove unwanted config paths
  ansible.builtin.set_fact:
    config_items: "{{ config_items | reject('match', '.*(' + dir_symlinks | join('|') + ')') | list }}"

- name: Check config_items files
  ansible.builtin.stat:
    path: "~/{{ item }}"
  with_items: "{{ vars.config_items }}"
  register: check_config_items

- name: Make backup parent directories for config_items files
  ansible.builtin.file:
    path: "{{ vars.backup_dir }}/{{ item.stat.path | dirname }}"
    state: directory
    mode: "0755"
  with_items: "{{ check_config_items.results | selectattr('stat.exists') | selectattr('stat.islnk', 'equalto', false) | list }}"

- name: Backup config_items files
  ansible.builtin.copy:
    src: "{{ item.stat.path }}"
    dest: "{{ vars.backup_dir }}/{{ item.stat.path }}"
    mode: "0644"
  with_items: "{{ check_config_items.results | selectattr('stat.exists') | selectattr('stat.islnk', 'equalto', false) | list }}"

- name: Remove config_items files
  ansible.builtin.file:
    path: "{{ item.stat.path }}"
    state: absent
  with_items: "{{ check_config_items.results | selectattr('stat.exists') | selectattr('stat.islnk', 'equalto', false) | list }}"

- name: Mkdir config paths
  ansible.builtin.file:
    path: "~/{{ item | dirname }}"
    state: directory
    mode: "0755"
  with_items: "{{ vars.config_items }}"

- name: Make config symlinks
  ansible.builtin.file:
    src: "{{ vars.config_dir }}/{{ item | regex_replace('^(\\.config|\\.local/share)/([^/]+)(.*)', '\\2/\\1\\3') }}"
    dest: "~/{{ item }}"
    state: link
  with_items: "{{ vars.config_items }}"

- name: Get direct home files from config directories
  ansible.builtin.set_fact:
    direct_home_files: "{{ config_paths | select('match', '^[^/]+/[^/]+$') | reject('match', '.*(' + replace_list | join('|') + ')') | list }}"

- name: Check direct home files
  ansible.builtin.stat:
    path: "~/{{ item | regex_replace('^[^/]+/', '') }}"
  with_items: "{{ vars.direct_home_files }}"
  register: check_direct_home_files

- name: Make backup parent directories for direct home files
  ansible.builtin.file:
    path: "{{ vars.backup_dir }}/{{ item.stat.path | dirname }}"
    state: directory
    mode: "0755"
  with_items: "{{ check_direct_home_files.results | selectattr('stat.exists') | selectattr('stat.islnk', 'equalto', false) | list }}"

- name: Backup direct home files
  ansible.builtin.copy:
    src: "{{ item.stat.path }}"
    dest: "{{ vars.backup_dir }}/{{ item.stat.path }}"
    mode: "0644"
  with_items: "{{ check_direct_home_files.results | selectattr('stat.exists') | selectattr('stat.islnk', 'equalto', false) | list }}"

- name: Remove direct home files
  ansible.builtin.file:
    path: "{{ item.stat.path }}"
    state: absent
  with_items: "{{ check_direct_home_files.results | selectattr('stat.exists') | selectattr('stat.islnk', 'equalto', false) | list }}"

- name: Make direct home symlinks
  ansible.builtin.file:
    src: "{{ vars.config_dir }}/{{ item }}"
    dest: "~/{{ item | regex_replace('^[^/]+/', '') }}"
    state: link
  with_items: "{{ vars.direct_home_files }}"
