- name: Set all config
  ansible.builtin.import_tasks: all.yml

- name: Set zsh
  ansible.builtin.import_tasks: zsh.yml

- name: Set iTerm2
  ansible.builtin.import_tasks: iterm2.yml

# - name: Set yazi
#   ansible.builtin.import_tasks: yazi.yml

- name: Set vscode
  ansible.builtin.include_tasks: vscode.yml
  with_items:
    - "Code"
    - "Code - Insiders"
  loop_control:
    loop_var: vscode_dir_name

- name: Set terraform
  ansible.builtin.import_tasks: terraform.yml

- name: Set root
  ansible.builtin.import_tasks: root.yml
