- name: Set all config
  ansible.builtin.import_tasks: all.yml

- name: Set iTerm2
  ansible.builtin.import_tasks: iterm2.yml
  when: ansible_facts['os_family'] == "Darwin"

# - name: Set yazi
#   ansible.builtin.import_tasks: yazi.yml

- name: Set vscode
  ansible.builtin.include_tasks: vscode.yml
  with_items:
    - "Code"
    - "Code - Insiders"
    - "Cursor"
  loop_control:
    loop_var: vscode_dir_name
