- name: Check finicky files in ~/
  ansible.builtin.stat:
    path: "{{ item | replace(vars.config_dir + '/finicky/', '~/') }}"
  with_fileglob:
    - "{{ vars.config_dir }}/finicky/.*"
  register: finicky_files

- name: Remove finicky files in ~/
  ansible.builtin.file:
    path: "{{ item.stat.path }}"
    state: absent
  when: item.stat.exists and not item.stat.islnk
  with_items: "{{ finicky_files.results }}"

- name: Make finicky symlink to ~/
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ item | replace(vars.config_dir + '/finicky/', '~/') }}"
    state: link
  with_fileglob:
    - "{{ vars.config_dir }}/finicky/.*"
