- name: Check .terraformrc in ~/
  ansible.builtin.stat:
    path: "~/.terraformrc"
  register: terraformrc_file

- name: Remove .terraformrc in ~/
  ansible.builtin.file:
    path: "{{ terraformrc_file.stat.path }}"
    state: absent
  when: terraformrc_file.stat.exists and not terraformrc_file.stat.islnk

- name: Get $GOBIN
  ansible.builtin.shell: "echo $GOBIN"
  changed_when: false
  when: true
  register: gobin

- name: Set $GOBIN
  ansible.builtin.set_fact:
    go_bin_path: "{{ gobin.stdout }}"
  when: gobin.stdout != ""

- name: Make config_dir/terraform
  ansible.builtin.template:
    src: "terraform/.terraformrc.j2"
    dest: "{{ vars.config_dir }}/terraform/.terraformrc"
    mode: "0644"

- name: Make .terraformrc symlink to ~/
  ansible.builtin.file:
    src: "{{ vars.config_dir }}/terraform/.terraformrc"
    dest: "~/.terraformrc"
    state: link
