version: "2"
linters:
  default: all
  disable:
    - depguard
    - revive
  exclusions:
    paths:
      - gen
    rules:
      - path: ".*_test.go"
        linters:
          - containedctx
          - funlen
          - varnamelen
          - nestif
          - gocognit
          - tparallel
          - cyclop
          - dupl
