[manager]
prepend_keymap = [
  { on = "Q", run = "quit", desc = "Quit the process" },
  { on = "q", run = "quit --no-cwd-file", desc = "Quit the process without outputting cwd-file" },
  { on = "T", run = "plugin --sync max-preview", desc = "Maximize or restore preview" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  { on = "D", run = "plugin diff", desc = "Diff the selected with the hovered file" },
]
